"""init_db

Revision ID: 3a5e3cfca71f
Revises: 54a2a03ba7a8
Create Date: 2022-05-27 00:19:01.364864

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3a5e3cfca71f'
down_revision = '54a2a03ba7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    region_table = op.create_table('region',
                                   sa.Column('id', sa.Integer(), nullable=False),
                                   sa.Column('name', sa.String(length=255), nullable=False, comment='地区名称'),
                                   sa.Column('numeric', sa.String(length=3), nullable=False, comment='地区三位数字码'),
                                   sa.Column('code', sa.String(length=3), nullable=False, comment='地区三位码'),
                                   sa.PrimaryKeyConstraint('id')
                                   )
    op.create_index('code_idx_3a5aa32c', 'region', ['code'], unique=False)
    op.create_index('id_idx_6f5f1f91', 'region', ['id'], unique=False)
    op.create_index('numeric_idx_f8c3b7a6', 'region', ['numeric'], unique=False)
    op.create_table('ip',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.String(length=255), nullable=False, comment='Ip address'),
                    sa.Column('region_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('id_idx_2bcb7644', 'ip', ['id'], unique=False)
    op.create_index('region_id_idx_9c7532be', 'ip', ['region_id'], unique=False)
    op.create_index('value_idx_5571c34a', 'ip', ['value'], unique=False)
    op.create_table('proxy',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('protocol', sa.String(length=6), nullable=False, comment='代理 IP 的 schema'),
                    sa.Column('port', sa.Integer(), nullable=False),
                    sa.Column('ip_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['ip_id'], ['ip.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('id_idx_0aa99d16', 'proxy', ['id'], unique=False)
    op.create_index('ip_id_idx_9160aafd', 'proxy', ['ip_id'], unique=False)
    op.create_table('scene',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('alive_count', sa.Integer(), nullable=False, comment='存活计数。可用加一，不可用减一'),
                    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最近一次更新时间'),
                    sa.Column('proxy_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('id_idx_83a604b6', 'scene', ['id'], unique=False)
    op.create_index('name_idx_e755c362', 'scene', ['name'], unique=False)
    op.create_index('proxy_id_idx_30b08a16', 'scene', ['proxy_id'], unique=False)

    op.bulk_insert(
        region_table,
        [{'name': 'Afghanistan', 'code': 'AFG', 'numeric': '004'},
         {'name': 'Åland Islands', 'code': 'ALA', 'numeric': '248'},
         {'name': 'Albania', 'code': 'ALB', 'numeric': '008'}, {'name': 'Algeria', 'code': 'DZA', 'numeric': '012'},
         {'name': 'American Samoa', 'code': 'ASM', 'numeric': '016'},
         {'name': 'Andorra', 'code': 'AND', 'numeric': '020'}, {'name': 'Angola', 'code': 'AGO', 'numeric': '024'},
         {'name': 'Anguilla', 'code': 'AIA', 'numeric': '660'}, {'name': 'Antarctica', 'code': 'ATA', 'numeric': '010'},
         {'name': 'Antigua and Barbuda', 'code': 'ATG', 'numeric': '028'},
         {'name': 'Argentina', 'code': 'ARG', 'numeric': '032'}, {'name': 'Armenia', 'code': 'ARM', 'numeric': '051'},
         {'name': 'Aruba', 'code': 'ABW', 'numeric': '533'}, {'name': 'Australia', 'code': 'AUS', 'numeric': '036'},
         {'name': 'Austria', 'code': 'AUT', 'numeric': '040'}, {'name': 'Azerbaijan', 'code': 'AZE', 'numeric': '031'},
         {'name': 'Bahamas', 'code': 'BHS', 'numeric': '044'}, {'name': 'Bahrain', 'code': 'BHR', 'numeric': '048'},
         {'name': 'Bangladesh', 'code': 'BGD', 'numeric': '050'}, {'name': 'Barbados', 'code': 'BRB', 'numeric': '052'},
         {'name': 'Belarus', 'code': 'BLR', 'numeric': '112'}, {'name': 'Belgium', 'code': 'BEL', 'numeric': '056'},
         {'name': 'Belize', 'code': 'BLZ', 'numeric': '084'}, {'name': 'Benin', 'code': 'BEN', 'numeric': '204'},
         {'name': 'Bermuda', 'code': 'BMU', 'numeric': '060'}, {'name': 'Bhutan', 'code': 'BTN', 'numeric': '064'},
         {'name': 'Bolivia (Plurinational State of)', 'code': 'BOL', 'numeric': '068'},
         {'name': 'Bonaire, Sint Eustatius and Saba', 'code': 'BES', 'numeric': '535'},
         {'name': 'Bosnia and Herzegovina', 'code': 'BIH', 'numeric': '070'},
         {'name': 'Botswana', 'code': 'BWA', 'numeric': '072'},
         {'name': 'Bouvet Island', 'code': 'BVT', 'numeric': '074'},
         {'name': 'Brazil', 'code': 'BRA', 'numeric': '076'},
         {'name': 'British Indian Ocean Territory', 'code': 'IOT', 'numeric': '086'},
         {'name': 'Brunei Darussalam', 'code': 'BRN', 'numeric': '096'},
         {'name': 'Bulgaria', 'code': 'BGR', 'numeric': '100'},
         {'name': 'Burkina Faso', 'code': 'BFA', 'numeric': '854'},
         {'name': 'Burundi', 'code': 'BDI', 'numeric': '108'}, {'name': 'Cabo Verde', 'code': 'CPV', 'numeric': '132'},
         {'name': 'Cambodia', 'code': 'KHM', 'numeric': '116'}, {'name': 'Cameroon', 'code': 'CMR', 'numeric': '120'},
         {'name': 'Canada', 'code': 'CAN', 'numeric': '124'},
         {'name': 'Cayman Islands', 'code': 'CYM', 'numeric': '136'},
         {'name': 'Central African Republic', 'code': 'CAF', 'numeric': '140'},
         {'name': 'Chad', 'code': 'TCD', 'numeric': '148'}, {'name': 'Chile', 'code': 'CHL', 'numeric': '152'},
         {'name': 'China', 'code': 'CHN', 'numeric': '156'},
         {'name': 'Christmas Island', 'code': 'CXR', 'numeric': '162'},
         {'name': 'Cocos (Keeling) Islands', 'code': 'CCK', 'numeric': '166'},
         {'name': 'Colombia', 'code': 'COL', 'numeric': '170'}, {'name': 'Comoros', 'code': 'COM', 'numeric': '174'},
         {'name': 'Congo', 'code': 'COG', 'numeric': '178'},
         {'name': 'Congo, Democratic Republic of the', 'code': 'COD', 'numeric': '180'},
         {'name': 'Cook Islands', 'code': 'COK', 'numeric': '184'},
         {'name': 'Costa Rica', 'code': 'CRI', 'numeric': '188'},
         {'name': "Côte d'Ivoire", 'code': 'CIV', 'numeric': '384'},
         {'name': 'Croatia', 'code': 'HRV', 'numeric': '191'}, {'name': 'Cuba', 'code': 'CUB', 'numeric': '192'},
         {'name': 'Curaçao', 'code': 'CUW', 'numeric': '531'}, {'name': 'Cyprus', 'code': 'CYP', 'numeric': '196'},
         {'name': 'Czechia', 'code': 'CZE', 'numeric': '203'}, {'name': 'Denmark', 'code': 'DNK', 'numeric': '208'},
         {'name': 'Djibouti', 'code': 'DJI', 'numeric': '262'}, {'name': 'Dominica', 'code': 'DMA', 'numeric': '212'},
         {'name': 'Dominican Republic', 'code': 'DOM', 'numeric': '214'},
         {'name': 'Ecuador', 'code': 'ECU', 'numeric': '218'}, {'name': 'Egypt', 'code': 'EGY', 'numeric': '818'},
         {'name': 'El Salvador', 'code': 'SLV', 'numeric': '222'},
         {'name': 'Equatorial Guinea', 'code': 'GNQ', 'numeric': '226'},
         {'name': 'Eritrea', 'code': 'ERI', 'numeric': '232'}, {'name': 'Estonia', 'code': 'EST', 'numeric': '233'},
         {'name': 'Eswatini', 'code': 'SWZ', 'numeric': '748'}, {'name': 'Ethiopia', 'code': 'ETH', 'numeric': '231'},
         {'name': 'Falkland Islands (Malvinas)', 'code': 'FLK', 'numeric': '238'},
         {'name': 'Faroe Islands', 'code': 'FRO', 'numeric': '234'}, {'name': 'Fiji', 'code': 'FJI', 'numeric': '242'},
         {'name': 'Finland', 'code': 'FIN', 'numeric': '246'}, {'name': 'France', 'code': 'FRA', 'numeric': '250'},
         {'name': 'French Guiana', 'code': 'GUF', 'numeric': '254'},
         {'name': 'French Polynesia', 'code': 'PYF', 'numeric': '258'},
         {'name': 'French Southern Territories', 'code': 'ATF', 'numeric': '260'},
         {'name': 'Gabon', 'code': 'GAB', 'numeric': '266'}, {'name': 'Gambia', 'code': 'GMB', 'numeric': '270'},
         {'name': 'Georgia', 'code': 'GEO', 'numeric': '268'}, {'name': 'Germany', 'code': 'DEU', 'numeric': '276'},
         {'name': 'Ghana', 'code': 'GHA', 'numeric': '288'}, {'name': 'Gibraltar', 'code': 'GIB', 'numeric': '292'},
         {'name': 'Greece', 'code': 'GRC', 'numeric': '300'}, {'name': 'Greenland', 'code': 'GRL', 'numeric': '304'},
         {'name': 'Grenada', 'code': 'GRD', 'numeric': '308'}, {'name': 'Guadeloupe', 'code': 'GLP', 'numeric': '312'},
         {'name': 'Guam', 'code': 'GUM', 'numeric': '316'}, {'name': 'Guatemala', 'code': 'GTM', 'numeric': '320'},
         {'name': 'Guernsey', 'code': 'GGY', 'numeric': '831'}, {'name': 'Guinea', 'code': 'GIN', 'numeric': '324'},
         {'name': 'Guinea-Bissau', 'code': 'GNB', 'numeric': '624'},
         {'name': 'Guyana', 'code': 'GUY', 'numeric': '328'}, {'name': 'Haiti', 'code': 'HTI', 'numeric': '332'},
         {'name': 'Heard Island and McDonald Islands', 'code': 'HMD', 'numeric': '334'},
         {'name': 'Holy See', 'code': 'VAT', 'numeric': '336'}, {'name': 'Honduras', 'code': 'HND', 'numeric': '340'},
         {'name': 'Hong Kong', 'code': 'HKG', 'numeric': '344'}, {'name': 'Hungary', 'code': 'HUN', 'numeric': '348'},
         {'name': 'Iceland', 'code': 'ISL', 'numeric': '352'}, {'name': 'India', 'code': 'IND', 'numeric': '356'},
         {'name': 'Indonesia', 'code': 'IDN', 'numeric': '360'},
         {'name': 'Iran (Islamic Republic of)', 'code': 'IRN', 'numeric': '364'},
         {'name': 'Iraq', 'code': 'IRQ', 'numeric': '368'}, {'name': 'Ireland', 'code': 'IRL', 'numeric': '372'},
         {'name': 'Isle of Man', 'code': 'IMN', 'numeric': '833'}, {'name': 'Israel', 'code': 'ISR', 'numeric': '376'},
         {'name': 'Italy', 'code': 'ITA', 'numeric': '380'}, {'name': 'Jamaica', 'code': 'JAM', 'numeric': '388'},
         {'name': 'Japan', 'code': 'JPN', 'numeric': '392'}, {'name': 'Jersey', 'code': 'JEY', 'numeric': '832'},
         {'name': 'Jordan', 'code': 'JOR', 'numeric': '400'}, {'name': 'Kazakhstan', 'code': 'KAZ', 'numeric': '398'},
         {'name': 'Kenya', 'code': 'KEN', 'numeric': '404'}, {'name': 'Kiribati', 'code': 'KIR', 'numeric': '296'},
         {'name': "Korea (Democratic People's Republic of)", 'code': 'PRK', 'numeric': '408'},
         {'name': 'Korea, Republic of', 'code': 'KOR', 'numeric': '410'},
         {'name': 'Kuwait', 'code': 'KWT', 'numeric': '414'}, {'name': 'Kyrgyzstan', 'code': 'KGZ', 'numeric': '417'},
         {'name': "Lao People's Democratic Republic", 'code': 'LAO', 'numeric': '418'},
         {'name': 'Latvia', 'code': 'LVA', 'numeric': '428'}, {'name': 'Lebanon', 'code': 'LBN', 'numeric': '422'},
         {'name': 'Lesotho', 'code': 'LSO', 'numeric': '426'}, {'name': 'Liberia', 'code': 'LBR', 'numeric': '430'},
         {'name': 'Libya', 'code': 'LBY', 'numeric': '434'}, {'name': 'Liechtenstein', 'code': 'LIE', 'numeric': '438'},
         {'name': 'Lithuania', 'code': 'LTU', 'numeric': '440'},
         {'name': 'Luxembourg', 'code': 'LUX', 'numeric': '442'}, {'name': 'Macao', 'code': 'MAC', 'numeric': '446'},
         {'name': 'Madagascar', 'code': 'MDG', 'numeric': '450'}, {'name': 'Malawi', 'code': 'MWI', 'numeric': '454'},
         {'name': 'Malaysia', 'code': 'MYS', 'numeric': '458'}, {'name': 'Maldives', 'code': 'MDV', 'numeric': '462'},
         {'name': 'Mali', 'code': 'MLI', 'numeric': '466'}, {'name': 'Malta', 'code': 'MLT', 'numeric': '470'},
         {'name': 'Marshall Islands', 'code': 'MHL', 'numeric': '584'},
         {'name': 'Martinique', 'code': 'MTQ', 'numeric': '474'},
         {'name': 'Mauritania', 'code': 'MRT', 'numeric': '478'},
         {'name': 'Mauritius', 'code': 'MUS', 'numeric': '480'}, {'name': 'Mayotte', 'code': 'MYT', 'numeric': '175'},
         {'name': 'Mexico', 'code': 'MEX', 'numeric': '484'},
         {'name': 'Micronesia (Federated States of)', 'code': 'FSM', 'numeric': '583'},
         {'name': 'Moldova, Republic of', 'code': 'MDA', 'numeric': '498'},
         {'name': 'Monaco', 'code': 'MCO', 'numeric': '492'}, {'name': 'Mongolia', 'code': 'MNG', 'numeric': '496'},
         {'name': 'Montenegro', 'code': 'MNE', 'numeric': '499'},
         {'name': 'Montserrat', 'code': 'MSR', 'numeric': '500'}, {'name': 'Morocco', 'code': 'MAR', 'numeric': '504'},
         {'name': 'Mozambique', 'code': 'MOZ', 'numeric': '508'}, {'name': 'Myanmar', 'code': 'MMR', 'numeric': '104'},
         {'name': 'Namibia', 'code': 'NAM', 'numeric': '516'}, {'name': 'Nauru', 'code': 'NRU', 'numeric': '520'},
         {'name': 'Nepal', 'code': 'NPL', 'numeric': '524'}, {'name': 'Netherlands', 'code': 'NLD', 'numeric': '528'},
         {'name': 'New Caledonia', 'code': 'NCL', 'numeric': '540'},
         {'name': 'New Zealand', 'code': 'NZL', 'numeric': '554'},
         {'name': 'Nicaragua', 'code': 'NIC', 'numeric': '558'}, {'name': 'Niger', 'code': 'NER', 'numeric': '562'},
         {'name': 'Nigeria', 'code': 'NGA', 'numeric': '566'}, {'name': 'Niue', 'code': 'NIU', 'numeric': '570'},
         {'name': 'Norfolk Island', 'code': 'NFK', 'numeric': '574'},
         {'name': 'North Macedonia', 'code': 'MKD', 'numeric': '807'},
         {'name': 'Northern Mariana Islands', 'code': 'MNP', 'numeric': '580'},
         {'name': 'Norway', 'code': 'NOR', 'numeric': '578'}, {'name': 'Oman', 'code': 'OMN', 'numeric': '512'},
         {'name': 'Pakistan', 'code': 'PAK', 'numeric': '586'}, {'name': 'Palau', 'code': 'PLW', 'numeric': '585'},
         {'name': 'Palestine, State of', 'code': 'PSE', 'numeric': '275'},
         {'name': 'Panama', 'code': 'PAN', 'numeric': '591'},
         {'name': 'Papua New Guinea', 'code': 'PNG', 'numeric': '598'},
         {'name': 'Paraguay', 'code': 'PRY', 'numeric': '600'}, {'name': 'Peru', 'code': 'PER', 'numeric': '604'},
         {'name': 'Philippines', 'code': 'PHL', 'numeric': '608'},
         {'name': 'Pitcairn', 'code': 'PCN', 'numeric': '612'}, {'name': 'Poland', 'code': 'POL', 'numeric': '616'},
         {'name': 'Portugal', 'code': 'PRT', 'numeric': '620'},
         {'name': 'Puerto Rico', 'code': 'PRI', 'numeric': '630'}, {'name': 'Qatar', 'code': 'QAT', 'numeric': '634'},
         {'name': 'Réunion', 'code': 'REU', 'numeric': '638'}, {'name': 'Romania', 'code': 'ROU', 'numeric': '642'},
         {'name': 'Russian Federation', 'code': 'RUS', 'numeric': '643'},
         {'name': 'Rwanda', 'code': 'RWA', 'numeric': '646'},
         {'name': 'Saint Barthélemy', 'code': 'BLM', 'numeric': '652'},
         {'name': 'Saint Helena, Ascension and Tristan da Cunha', 'code': 'SHN', 'numeric': '654'},
         {'name': 'Saint Kitts and Nevis', 'code': 'KNA', 'numeric': '659'},
         {'name': 'Saint Lucia', 'code': 'LCA', 'numeric': '662'},
         {'name': 'Saint Martin (French part)', 'code': 'MAF', 'numeric': '663'},
         {'name': 'Saint Pierre and Miquelon', 'code': 'SPM', 'numeric': '666'},
         {'name': 'Saint Vincent and the Grenadines', 'code': 'VCT', 'numeric': '670'},
         {'name': 'Samoa', 'code': 'WSM', 'numeric': '882'}, {'name': 'San Marino', 'code': 'SMR', 'numeric': '674'},
         {'name': 'Sao Tome and Principe', 'code': 'STP', 'numeric': '678'},
         {'name': 'Saudi Arabia', 'code': 'SAU', 'numeric': '682'},
         {'name': 'Senegal', 'code': 'SEN', 'numeric': '686'}, {'name': 'Serbia', 'code': 'SRB', 'numeric': '688'},
         {'name': 'Seychelles', 'code': 'SYC', 'numeric': '690'},
         {'name': 'Sierra Leone', 'code': 'SLE', 'numeric': '694'},
         {'name': 'Singapore', 'code': 'SGP', 'numeric': '702'},
         {'name': 'Sint Maarten (Dutch part)', 'code': 'SXM', 'numeric': '534'},
         {'name': 'Slovakia', 'code': 'SVK', 'numeric': '703'}, {'name': 'Slovenia', 'code': 'SVN', 'numeric': '705'},
         {'name': 'Solomon Islands', 'code': 'SLB', 'numeric': '090'},
         {'name': 'Somalia', 'code': 'SOM', 'numeric': '706'},
         {'name': 'South Africa', 'code': 'ZAF', 'numeric': '710'},
         {'name': 'South Georgia and the South Sandwich Islands', 'code': 'SGS', 'numeric': '239'},
         {'name': 'South Sudan', 'code': 'SSD', 'numeric': '728'}, {'name': 'Spain', 'code': 'ESP', 'numeric': '724'},
         {'name': 'Sri Lanka', 'code': 'LKA', 'numeric': '144'}, {'name': 'Sudan', 'code': 'SDN', 'numeric': '729'},
         {'name': 'Suriname', 'code': 'SUR', 'numeric': '740'},
         {'name': 'Svalbard and Jan Mayen', 'code': 'SJM', 'numeric': '744'},
         {'name': 'Sweden', 'code': 'SWE', 'numeric': '752'}, {'name': 'Switzerland', 'code': 'CHE', 'numeric': '756'},
         {'name': 'Syrian Arab Republic', 'code': 'SYR', 'numeric': '760'},
         {'name': 'Taiwan, Province of China', 'code': 'TWN', 'numeric': '158'},
         {'name': 'Tajikistan', 'code': 'TJK', 'numeric': '762'},
         {'name': 'Tanzania, United Republic of', 'code': 'TZA', 'numeric': '834'},
         {'name': 'Thailand', 'code': 'THA', 'numeric': '764'},
         {'name': 'Timor-Leste', 'code': 'TLS', 'numeric': '626'}, {'name': 'Togo', 'code': 'TGO', 'numeric': '768'},
         {'name': 'Tokelau', 'code': 'TKL', 'numeric': '772'}, {'name': 'Tonga', 'code': 'TON', 'numeric': '776'},
         {'name': 'Trinidad and Tobago', 'code': 'TTO', 'numeric': '780'},
         {'name': 'Tunisia', 'code': 'TUN', 'numeric': '788'}, {'name': 'Turkey', 'code': 'TUR', 'numeric': '792'},
         {'name': 'Turkmenistan', 'code': 'TKM', 'numeric': '795'},
         {'name': 'Turks and Caicos Islands', 'code': 'TCA', 'numeric': '796'},
         {'name': 'Tuvalu', 'code': 'TUV', 'numeric': '798'}, {'name': 'Uganda', 'code': 'UGA', 'numeric': '800'},
         {'name': 'Ukraine', 'code': 'UKR', 'numeric': '804'},
         {'name': 'United Arab Emirates', 'code': 'ARE', 'numeric': '784'},
         {'name': 'United Kingdom of Great Britain and Northern Ireland', 'code': 'GBR', 'numeric': '826'},
         {'name': 'United States of America', 'code': 'USA', 'numeric': '840'},
         {'name': 'United States Minor Outlying Islands', 'code': 'UMI', 'numeric': '581'},
         {'name': 'Uruguay', 'code': 'URY', 'numeric': '858'}, {'name': 'Uzbekistan', 'code': 'UZB', 'numeric': '860'},
         {'name': 'Vanuatu', 'code': 'VUT', 'numeric': '548'},
         {'name': 'Venezuela (Bolivarian Republic of)', 'code': 'VEN', 'numeric': '862'},
         {'name': 'Viet Nam', 'code': 'VNM', 'numeric': '704'},
         {'name': 'Virgin Islands (British)', 'code': 'VGB', 'numeric': '092'},
         {'name': 'Virgin Islands (U.S.)', 'code': 'VIR', 'numeric': '850'},
         {'name': 'Wallis and Futuna', 'code': 'WLF', 'numeric': '876'},
         {'name': 'Western Sahara', 'code': 'ESH', 'numeric': '732'},
         {'name': 'Yemen', 'code': 'YEM', 'numeric': '887'}, {'name': 'Zambia', 'code': 'ZMB', 'numeric': '894'},
         {'name': 'Zimbabwe', 'code': 'ZWE', 'numeric': '716'}]

    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('proxy_id_idx_30b08a16', table_name='scene')
    op.drop_index('name_idx_e755c362', table_name='scene')
    op.drop_index('id_idx_83a604b6', table_name='scene')
    op.drop_table('scene')
    op.drop_index('ip_id_idx_9160aafd', table_name='proxy')
    op.drop_index('id_idx_0aa99d16', table_name='proxy')
    op.drop_table('proxy')
    op.drop_index('value_idx_5571c34a', table_name='ip')
    op.drop_index('region_id_idx_9c7532be', table_name='ip')
    op.drop_index('id_idx_2bcb7644', table_name='ip')
    op.drop_table('ip')
    op.drop_index('numeric_idx_f8c3b7a6', table_name='region')
    op.drop_index('id_idx_6f5f1f91', table_name='region')
    op.drop_index('code_idx_3a5aa32c', table_name='region')
    op.drop_table('region')
    # ### end Alembic commands ###
