show_sql: false

# Enable verbose mode to show more log detail message
# Default is false
verbose: false
# Enable debug mode to show debug log.
# Default is false, if enable, will show debug log.
debug: false

# LOG
# Config log level, default is WARNING, if enable `debug` mode,
# log level is debug
loglevel: warning
# Config log path.
# default project path
logpath: logs

# Server

host: 127.0.0.1
port: 8000

default_page_limit: 20

# Database config.
# Default is sqlite+aiosqlite:////<project_path>/.local/proxypool.db
#database: sqlite+aiosqlite:////tmp/crawlerstack_proxypool
#database: mysql+aiomysql://user:password@host:port/dbname
#database: postgresql+asyncpg://user:password@host:port/dbname
database:

redis_url: redis://localhost

